version: "3.8"

services:

  accounts:
    image: easybytes/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - eazybank-network
    
  loans:
    image: easybytes/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - eazybank-network
    
  cards:
    image: easybytes/cards:latest
    mem_limit: 700m
    ports:
      - "9010:9010"
    networks:
      - eazybank-network
    
networks:
  eazybank-network: